version: '3'

services:
  ifconfig:
    image: localhost/ifconfig:latest
    environment:
      - PROXY_MODE=true
    ports:
      - "5000:5000"
    logging:
      driver: json-file
      options:
        max-size: 50m
